### ISSUE TITLE
Kernel panic - trans path oveflow [adc22c951]

### ISSUE THREAD

**Issue by RAOF** [koverstreet/bcachefs#513]
As of commit adc22c951.

While trying to reproduce the shrinker deadlock on a maximally-debugging kernel, I instead hit this panic. There was lots of activity at the time - an LLVM compile, a `bcachefs evacuate /dev/sdb2`, and so on - but no obvious single trigger.

[dmesg prior to and including the panic](https://github.com/koverstreet/bcachefs/files/10870195/netfilt.log)

**Comment by koverstreet** [comment]
02:30 <@py1hon> ooh, that                                                                                                                                       |
02:30 <@py1hon> you're running with a replication setup and lockdep enabled                                                                                     |
02:31 <@py1hon> we decrease the maximum number of btree paths when lockdep is enabled, because lockdep bugs out if you're holding more than 48 locks            |
                simultaneously                                                                                                                                  |
02:31 <@py1hon> but 32 paths is not enough anymore with replication                                                                                             |
02:31 <@py1hon> 64 won't be enough soon too

**Comment by koverstreet** [comment]
There's now a workaround for this merged - I'm going to try to hit up Peter Zijlstra at LSF and see if we can come up with something better.
