### ISSUE TITLE
Question: alternative hashing/error correction

### ISSUE THREAD

**Issue by gutleib** [koverstreet/bcachefs#6]
Hi.
Is there plans for alternative hashing algorithms, e.g. xxhash, being added to bcachefs? Crc32 is not an option for us due to collisions and dependency on cpu instruction set...
Or, do you have some guidelines for implementing alternative hash algorithms in your FS? Actually, we have something in mind, and afaik, one can face an issue only if crc_combine is used, since most of contemporary hash algorithms do not support such function.
As I understood from docs, you have no support for error correction for now... I am reading about solutions you mentioned. But, I can only hope that Reed-Solomon with it's high cpu demand wont be the only option (I beleive I've seen it's being mentioned somewhere in bugtracker).

**Comment by koverstreet** [comment]
Hash collisions aren't really an issue for when you're using a checksum as an integrity check, which is what we're using crc32c for. Or do you have some more specific concern...?

It might be worthwhile adding another option for architectures where crc32c is slow, but I don't know if that's actually an issue because crc32c is used pretty widely these days and tends to be quite well optimized.

**Comment by gutleib** [comment]
Are they? We have a concern about silent data corruption or post-replication checks. Yes, the probability is several magnitudes lower than without any checks, but modern algorithms make it even lower (especially if 64 bits hashsums are used instead of 32). If bcachefs is a "do as good as we can" effort, why a compromise? 

And yes, the second reason is speed. Here's a simple and very illustrative test, you will need only a KVM/QEMU VM with a cpu set as "generic" (recommended for VM smooth migration), any distro, and a fio v3 and later:
`fio --crctest
md5:              526.14 MiB/sec
crc64:            342.28 MiB/sec
crc32:            302.35 MiB/sec
crc32c:           347.21 MiB/sec
crc16:            353.16 MiB/sec
crc7:             354.51 MiB/sec
sha1:             487.09 MiB/sec
sha256:           180.38 MiB/sec
sha512:           304.55 MiB/sec
xxhash:          5670.62 MiB/sec
murmur3:         2262.50 MiB/sec
jhash:           2035.40 MiB/sec
fnv:             5654.83 MiB/sec
sha3-224:          39.69 MiB/sec
sha3-256:          37.83 MiB/sec
sha3-384:          28.49 MiB/sec
sha3-512:          19.95 MiB/sec`

We are using something even faster than XXhash, a [t1ha](https://github.com/leo-yuriev/t1ha). So far so good.

**Comment by gutleib** [comment]
On a second thought, I should probably explain what the above numbers are saying to me...

Afaik, crc32c is not that much optimized. It's CPUs, that have a specific instruction for it's calculation, that make it reasonably fast. But not all of them. Low end CPUs, or not-so-server CPUs might not have needed instruction set. And even when it is in place, crc32c not beyond competition:
```
fio --crctest
md5:      532.36 MB/sec
crc64:      346.67 MB/sec
crc32:      304.20 MB/sec
crc32c:     7508.43 MB/sec
crc16:      346.97 MB/sec
crc7:      351.66 MB/sec
sha1:      517.68 MB/sec
sha256:      205.40 MB/sec
sha512:      336.99 MB/sec
xxhash:     5593.67 MB/sec
murmur3:   2259.59 MB/sec
jhash:     2049.30 MB/sec
fnv:     5656.71 MB/sec
```
That's Intel Scalable, probably the newest arch on the market.
Difference between HW accelerated crc32c and universal SW calculated xxhash is around 25%. And t1ha 10-15% faster than xxhash. So, introducing an alternative to crc32c would probably change the overall speed only marginally, but make a huge difference on low-end platforms (MIPS, some ARMs, others).

I am not a coder myself, so, I might be incorrect in this, but that's what it seems from Scrum-PO point of view.

**Comment by koverstreet** [comment]
On Wed, Aug 22, 2018 at 01:49:01PM +0000, gutleib wrote:
> Are they? We have a concern about silent data corruption or post-replication
> checks. Yes, the probability is several magnitudes lower than without any
> checks, but modern algorithms make it even lower (especially if 64 bits
> hashsums are used instead of 32). If bcachefs is a "do as good as we can"
> effort, why a compromise? 

So, if the reason is you want something _stronger_ than crc32c - you need to be
aware that checksums for detecting data corruption have a different goal than
hashes which are trying to avoid collisions - CRCs (like crc32c) provide strong
mathematical guarantees that they will detect the kinds of random data
corruptions that are likely to occur in practice. Hash functions like
xxhash/murmur3/jhash aren't designed that way, they're meant to be good _on
average_ at avoiding collisions between unrelated data.

So I would be _really_ uncomfortable with adding something like xxhash without a
paper or some kind of other serious mathematical analysis justifying it for that
purpose.

And we do already have a 64 bit CRC, the current implementation is really
slow but postgresql has a newer much faster implementation that we can pull in
(that's where that CRC originally came from).

If you still want something stronger, or you want something stronger than crc32c
but fast, there's also poly1305 which is a cryptographic MAC, and the kernel
implementation is fast - I just tested it and it's 3474 MB/sec for me, running
inside a VM on a Haswell.

> And yes, the second reason is speed. Here's a simple and very illustrative
> test, you will need only a KVM/QEMU VM with a cpu set as "generic"
> (recommended for VM smooth migration), any distro, and a fio v3 and later:

You really don't want to run with your cpu set to generic, you lose out on any
new instructions from the past, what, 20 years. Just figure out what your common
denominator supported instruction set is.
